algoritmo "nome1"

"13. Ler um número inteiro (assuma até três dígitos) e imprimir a saída da seguinte forma: 
CENTENA = x 
DEZENA = x 
UNIDADE = x 
"

var

    numero: vetor[1..3] de caractere

inicio

    escreval ("Digite um número de até três digitos")
    leia (numero)


    escreval ("O primeiro número é o"numero[0])
    escreval ("O segundo número é o"numero[1])
    escreval ("O terceiro número é o"numero[2])


fimalgoritmo
