algoritmo "IMC calculator"

// Discipline: Algorithm and Programming Logic
// Professor: Pietro Martins de Oliveira
// Description: IMC calculator
// Author: Paulo R. Muniz
// Current date: 12/09/2023

var

height, weight, imc : real

inicio

escreval ("State your weight: ")
leia (weight)

escreval ("State your height: ")
leia (height)

imc <- (weight/(weight*weight))

escreva ("Your IMC is: ", imc)


fimalgoritmo