algoritmo "Triangle Area"

// Discipline: Algorithm and Programming Logic
// Professor: Pietro Martins de Oliveira
// Description: Calculate triangle area
// Author: Paulo R. Muniz
// Current date: 12/09/2023
var

area, base, height: real

inicio

escreval ("Triangle height: ")
leia (height)

escreval ("Triangle base: ")
leia (base)

area <- (base*height)/2

escreva ("Triangle area is: ", area)


fimalgoritmo